### ISSUE TITLE
update a date field to null 

### ISSUE THREAD

**Issue by GabCores** [crisfervil/DynamicsNode#12]
Hi @crisfervil  , I have this issue , trying to set to null a date , I get this error .

![image](https://cloud.githubusercontent.com/assets/12952699/20467732/446dc5c0-af6c-11e6-8883-f8ee74d85f49.png)

This is may code :

var account = {} ;
account.accountid = '7D0C0490-9934-E611-80C3-005056AC0018' ;
account.name =  "now3" ;
account.new_deliverdate =  null ;
crm.update("account", account );

What am I doing wrong , 
Thanks in advance .

**Comment by crisfervil** [comment]
Hi @GabrielGab. I'll have a look at this case and come back to you ASAP

**Comment by crisfervil** [comment]
@GabrielGab I've published the version 0.0.15 to npm. This should fix the problem. Please let me know if it works!

**Comment by GabCores** [comment]
Works fine! Thank you!
