### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by nhance** [crisfervil/DynamicsNode#14]
NPM install is failing because the `package.json` refers to `bin/commands.js` which is not part of the repository.

Error message:
```
npm ERR! Windows_NT 10.0.14965
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nick\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3
npm ERR! path C:\Users\nick\Source\Repos\foobar\node_modules\dynamicsnode\bin\commands.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\nick\Source\Repos\foobar\node_modules\dynamicsnode\bin\commands.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\nick\Source\Repos\foobar\node_modules\dynamicsnode\bin\commands.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nick\Source\Repos\foobar\npm-debug.log
```

Suggested resolution ideas:
- Allow the compiled files to be a part of the repository?
- Explore how other node modules built with typescript are shipped.. is this standard?
- Change the bin to use the typescript file instead?

I will explore these options, but it may be difficult to test.

**Comment by nhance** [comment]
Attempting to duplicate this fails. It appears to happen only when installing using a github install.

Please hold off while I investigate further.

**Comment by nhance** [comment]
Confirmed when installing via `npm install "crisfervil/DynamicsNode#master"`

**Comment by crisfervil** [comment]
I don't think the 3rd option would work.

To be honest, I've never tried to install it from github.

Why do you want to do this? If you want to test a modified version you are working on, maybe is easier to use the npm link command https://docs.npmjs.com/cli/link

**Comment by nhance** [comment]
Let's close this ticket, looks like I can install from a local directory.

You've been so incredibly helpful with these tickets. Thank you!

**Comment by crisfervil** [comment]
Thank you @nhance
