### ISSUE TITLE
Some functions missing 

### ISSUE THREAD

**Issue by GabCores** [crisfervil/DynamicsNode#2]
Hi  Cris , I see that in CRMBridge.cs are implemented some functions like associate and dissociate , but they are not exposed in the object model. Others like Create , Fetch , Delete , Update , are all working ok in my tests - on premise and online CRM organizations -
So i think that something is missing in CRMClient.js file, in order to expose all the functions located in  CRMBridge.js .

By the way - I really appreciate this library - long waiting for this kind of contribution - thanks 
Gabriel

**Comment by crisfervil** [comment]
Hi GabrielGab, 

You are righ! There are a lot of things missing! and this is one of them. 

Do you think you can help me with that? Would be a matter of adding those methods to dynamicsnode.d.ts file. 

If you create a Pull request with that change I'll appreciate that. 

Thanks!

**Comment by GabCores** [comment]
Ok @crisfervil , I will try during this week:. By the way I have in mind to write an article in http://www.comunidadcrm.com/  - Spanish CRM community - base on Edgejs and this module - in order to show the potential of its features and to gather some contributors for growing it up . it's ok to you ? , are you able to read Spanish ?
Thanks!

**Comment by crisfervil** [comment]
Hey @GabrielGab , it sounds perfect! If there's anything that I can help you with, just let me know. 

PS: Soy de Paraguay, asi que hablo mejor espaniol que ingles!

**Comment by GabCores** [comment]
Que bueno @crisfervil , yo he vivido en Argentina por muchos anios, ahora trabajo aqui y he hecho costumbre. Veo que hay gente de Sonoma en las stars, eso es bueno , es una consultora que aporta mucho a  la comunidad . Igual para los fixing y adding seguimos en ingles , pero es bueno contar con tu lengua materna para agilizar - la mia es italiano - no muy lejos  :-) . hasta pronto.

**Comment by GabCores** [comment]
Hi @crisfervil , the  CRMclient.js   have a reference to   /// <reference path="../typings/main.d.ts" /> , but I haven't found it on repo , is it important ??

**Comment by crisfervil** [comment]
I've removed all the /// references. Those are not required any more

**Comment by crisfervil** [comment]
@GabrielGab I've merged your #3 changes  . Hope it works well.

**Comment by GabCores** [comment]
@crisfervil  , at least , up to now , changes not interfare with conenction and other stuff , may be this night I will be testing the exports functions .
