### ISSUE TITLE
exporting/importing  entities 

### ISSUE THREAD

**Issue by GabCores** [crisfervil/DynamicsNode#4]
hi @crisfervil , I don't understand how I can get access to those funcionalities . 

I found this quote:
$ di export systemuser users.xml

But , is this a command of nodes module ?

need some help , thanks !

**Comment by crisfervil** [comment]
That command wasn't implemented yet. 
I'm going to leave this issue open as a reminder to give it high prority.
I'll let you know when's done.
In the mean time I've updated the documentation to reflect this.
Thanks

**Comment by GabCores** [comment]
Ok, so useful when it will be implemented . 
Are you planning to use edge-sql ?  edge-ps ? combine with CRM SDK access about .NET ?
By the way , I am doing my testing on :
    CRM 2011 – on premise 
    CRM 2015 -  on line 
And the basic CRUD – no fetch yet - , works OK

**Comment by crisfervil** [comment]
@GabrielGab I've implemented the export command. The use is described here: https://github.com/crisfervil/DynamicsNode/blob/master/doc/CommandsAndRepl.md

I'll let you know when the Import is implemented.

Any improvements or suggestions are welcome!

**Comment by crisfervil** [comment]
@GabrielGab regarding your question about the use of edge-sql or edge-ps, I've been thinking in another tool more oriented to data integration, for example between Dynamics CRM and SQL Server.

The tool is called Integrer and you can find more info here:
https://github.com/crisfervil/Integrer

Unfortunatelly, this is only an Idea, and there's no code on it yet.

**Comment by crisfervil** [comment]
Implemented the Import command. 
More info at https://github.com/crisfervil/DynamicsNode/blob/master/doc/CommandsAndRepl.md
