### ISSUE TITLE
Integration Test 

### ISSUE THREAD

**Issue by GabCores** [crisfervil/DynamicsNode#5]
@crisfervil  , I have discovered the integration Test files :+1:  so I followed the steps and run it . 
It's all ok for the new functions ( associate and dissociate ) , but arrives some other error for fetching .
 target : CRM 2011 - on premise -

Image attach , i will see it toninght 
![integrationtest](https://cloud.githubusercontent.com/assets/12952699/14685839/aad45cd8-070c-11e6-85e0-3bac48460c75.jpg)

Regards

**Comment by crisfervil** [comment]
@GabrielGab Do you have any more details about the FetchError?

**Comment by GabCores** [comment]
@crisfervil , no time enough for deep testings , this weekend I will be able to , and report for details,.
Regards

**Comment by GabCores** [comment]
@crisfervil  , may be are you searching for this ?? tell me if you more or diverse info - the same as text ?? -- 
![fetcherror](https://cloud.githubusercontent.com/assets/12952699/14741996/49bede18-0870-11e6-8fdb-1c2fca2d9a80.jpg)

**Comment by GabCores** [comment]
@crisfervil  , 
   The fetch error is for crm 2011 - on premise and  
   CRM 2015 - On line

**Comment by crisfervil** [comment]
Hi @GabrielGab , 

Apparently,this is an issue with the Time Zone and the convertion to UTC in the test that is failing. 

I've commited a change a3b5f77 that may correct the problem. Could you get the latest version and try it please?

Thanks

**Comment by GabCores** [comment]
Ok, éxito , congrats !
![2016-04-25 18_38_35-simbolo del sistema](https://cloud.githubusercontent.com/assets/12952699/14799899/15745514-0b15-11e6-8041-ffc469157ae2.png)

**Comment by crisfervil** [comment]
👍
