### ISSUE TITLE
Needs a License

### ISSUE THREAD

**Issue by nicknow** [crisfervil/DynamicsNode#7]
Please add a LICENSE.MD file to this project. I can't find any licensing information and therefore I can't bring into a project, since I don't know the terms of use.

GitHub makes this very easy (http://stackoverflow.com/a/31666878/394978). I usually use the MIT License but the copyright owner gets to choose.

**Comment by MatheusJacob** [comment]
[2]

**Comment by crisfervil** [comment]
Added MIT licence to the project
